services:
  db:
    image: postgres:16.1
    container_name: share-it
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://dbuser:12345@db:5432/shareit -v ON_ERROR_STOP=1 <<-EOSQL
        DO \$\$ 
          DECLARE
            r RECORD;
          BEGIN
            FOR r IN (
              SELECT schemaname, tablename
              FROM pg_tables
              WHERE schemaname = 'public'
            ) LOOP
              EXECUTE 'DROP TABLE IF EXISTS '
                || quote_ident(r.schemaname) || '.'
                || quote_ident(r.tablename) || ' CASCADE';
            END LOOP;
        END \$\$;
        EOSQL
