spring.main.log-startup-info=false
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=dbuser
spring.datasource.password=12345

hibernate.jdbc.time-zone=UTC
hibernate.default-schema=public

logging.level.root=info
