CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(255) NULL,
    requestor_id int8 NOT NULL,
    created timestamp without time zone NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_requests_users_id FOREIGN KEY (requestor_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name varchar(100) NOT NULL,
    description varchar(255) NULL,
    available bool NOT NULL,
    owner_id int8 NULL,
    request_id int8 NULL,
    CONSTRAINT pk_items PRIMARY KEY (id),
    CONSTRAINT fk_items_users_id FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_items_requests_id FOREIGN KEY (request_id) REFERENCES public.requests(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.booking (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date timestamp without time zone NOT NULL NOT NULL,
    end_date timestamp without time zone NOT NULL,
    item_id bigint NOT NULL,
    booker_id bigint NOT NULL,
    status varchar(255) check (status in ('WAITING','APPROVED','REJECTED','CANCELED')),
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booking_items_id FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_users_id FOREIGN KEY (booker_id) REFERENCES public.users(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS public.comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id bigint NOT NULL,
    author_id bigint NOT NULL,
    created_date timestamp without time zone NOT NULL,
    comment_text VARCHAR(255) NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_items_id FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_users_id FOREIGN KEY (item_id) REFERENCES public.users(id) ON DELETE CASCADE
);
