server.port=9090

spring.main.banner-mode=OFF
spring.data.jdbc.dialect=POSTGRESQL
spring.sql.init.mode=ALWAYS

hibernate.jdbc.time-zone=UTC
hibernate.default-schema=public
hibernate.show-sql=true
hibernate.format-sql=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.indent_output=true
#---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=shareit
spring.datasource.password=shareit
#---
logging.level.root=error
logging.level.org.springframework.boot.web=info
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.zalando.logbook=TRACE
