package ru.practicum.shareit.util.datetime;

import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;

import java.time.*;

/// Generated by GPT
public class FutureOrPresentWithToleranceValidator
		implements ConstraintValidator<FutureOrPresentWithTolerance, Object> {

	private long toleranceMillis;
	private String zoneIdStr;
	private TimeRoundingStrategy roundingStrategy;

	@Override
	public void initialize(FutureOrPresentWithTolerance constraintAnnotation) {
		this.toleranceMillis = constraintAnnotation.toleranceMillis();
		this.zoneIdStr = constraintAnnotation.zone();
		this.roundingStrategy = constraintAnnotation.rounding();
	}

	@Override
	public boolean isValid(Object value, ConstraintValidatorContext context) {
		if (value == null) {
			return true;
		}

		Clock clock = context.getClockProvider().getClock();

		ZoneId zone = resolveZone(clock);

		Instant now = applyRounding(clock.instant());
		Instant valueInstant = toInstant(value, zone);

		if (valueInstant == null) {
			return false;
		}

		valueInstant = applyRounding(valueInstant);

		return valueInstant.toEpochMilli() >= (now.toEpochMilli() - toleranceMillis);
	}

	private ZoneId resolveZone(Clock clock) {
		if (zoneIdStr == null || zoneIdStr.isBlank()) {
			return clock.getZone();
		}
		return ZoneId.of(zoneIdStr);
	}

	private Instant toInstant(Object value, ZoneId zone) {

		if (value instanceof Instant) {
			return (Instant) value;
		}

		if (value instanceof OffsetDateTime) {
			return ((OffsetDateTime) value).toInstant();
		}

		if (value instanceof ZonedDateTime) {
			return ((ZonedDateTime) value).toInstant();
		}

		if (value instanceof LocalDateTime) {
			return ((LocalDateTime) value).atZone(zone).toInstant();
		}

		if (value instanceof LocalDate) {
			return ((LocalDate) value).atStartOfDay(zone).toInstant();
		}

		return null;
	}

	private Instant applyRounding(Instant instant) {

		switch (roundingStrategy) {

			case TRUNCATE_TO_SECONDS:
				return instant.truncatedTo(java.time.temporal.ChronoUnit.SECONDS);

			case TRUNCATE_TO_MINUTES:
				return instant.truncatedTo(java.time.temporal.ChronoUnit.MINUTES);

			case ROUND_TO_SECONDS:
				long millis = instant.toEpochMilli();
				long rounded = Math.round(millis / 1000.0) * 1000;
				return Instant.ofEpochMilli(rounded);

			default:
				return instant;
		}
	}
}
