package ru.practicum.shareit.util.datetime;

import jakarta.validation.Constraint;
import jakarta.validation.Payload;

import java.lang.annotation.*;

/// Generated by GPT
@Documented
@Constraint(validatedBy = FutureOrPresentWithToleranceValidator.class)
@Target({ ElementType.FIELD, ElementType.PARAMETER })
@Retention(RetentionPolicy.RUNTIME)
public @interface FutureOrPresentWithTolerance {

	String message() default "must be in the present or future (with tolerance)";

	Class<?>[] groups() default {};

	Class<? extends Payload>[] payload() default {};

	long toleranceMillis() default 0;

	String zone() default "";

	TimeRoundingStrategy rounding() default TimeRoundingStrategy.NONE;
}
